[toolchain]

[features]
seeds = false
skip-lint = false
init-if-needed = true

[programs.localnet]
deopp_contract = "367SGmqLTxrfkicD6HhfJhVunmrhazwjAUpLH5mzi46F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tuotu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
