[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
deopp_contract = "BT63sTcG9tPNf2mxgzGaohQwPF8rC4mWSHAgxtW5QZDC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "/Users/tuotu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
